Conf:
  Mode: local
Local:
  Sysconf:
    FlushPathMapSpan: 60000 # ms, flush db api configuration to local process memory per interval
    LogConfigFile: log.xml # default 'log.xml 'with the startup binary file int the same dir, if not config
    Env: dev # dev、test、prd
  CORS:
    AccessControlAllowOrigin: '*'
    AccessControlAllowMethods: POST, GET, OPTIONS, PUT, DELETE
    AccessControlAllowHeaders: G-tenant,channel,agentChannel,token,did,lang,securityToken,deviceRam,userToken
  Http:
    ServicePort: 7777
    ServerReadTimeout: 1000 # ms, proxy server keepalive the tenant invoker connection
    ServerKeepalive: 3000 # ms, proxy server keepalive the tenant invoker connection
    GracefulShutdownTimeout: 60000 # ms, default '30s' if not config, means interrupt or kill server will max waiting for received request process
  DB:
    DBType: mysql
    ConnectionString: root:yicai.liu@tcp(39.99.150.175:3306)/api_gateway_v2?charset=utf8&parseTime=True
    LogMode: true
    MaxOpenConns: 10
    MaxIdleConns: 5
    ConnMaxIdleTime: 30000 # ms
  Redis:
    Addresses: localhost:6379
    Password:
    DB: 0
    PoolSize: 0
    DialTimeout: 100
    ReadTimeout: 100
    WriteTimeout: 100
    IdleTimeout: 900000 # 15 min=15*60*1000 ms=900000 ms
    MinIdleConns: 8
    MaxRetries: 0
    DetectAliveInterval: 1000 # ms
  Rate:
    Enable: true # default 'true' if not config, means api rate limit control
    LocalRateDownPercent: 20
  Routing:
    RequestTimeout: 30000 # default no timeout if not config
    MaxConnsPerHost: 20000
    MaxIdleConnsPerHost: 200
    MaxIdleConns: 1000
    IdleConnTimeout: 60000 # ms
  Monitor:
    LogDir: # default "" if not config , means current dir
    LogFileName: # default monitor.log if not config
    LogRotateMaxsize:  # unit(M), default 100M if not config
    LogRotateMaxLines: # default 50W if not config
