Conf:
  Mode: local
  Env: dev # dev、test、prd

Nacos:
  Address: 39.99.150.175:8848
  Namespace: dev
  DataId: life-gateway
  Group: DEFAULT_GROUP

Local:
  Sysconf:
    ServicePort: 7777
    FlushPathMapSpan: 60000
    ServerReadTimeout: 1000
    ServerKeepalive: 3000
    GracefulShutdownTimeout: 60000
    LogConfigFile: /Users/liuyicai/work/log.xml # default 'log.xml 'with the startup binary file int the same dir, if not config
  DB:
    DBType: mysql
    ConnectionString: root:yicai.liu@tcp(39.99.150.175:3306)/api_gateway?charset=utf8&parseTime=True
    LogMode: true
    MaxOpenConns: 10
    MaxIdleConns: 5
    ConnMaxIdleTime: 30000
  Redis:
    Mode: node
    Address: localhost:6379
    Password:
    DetectAliveInterval: 1000
  Rate:
    Enable: true
    Mode: server # server - limit the server actually rate; client - limit the tenant caller rate
  Routing:
    RequestTimeout: 5000
  Monitor:
    LogDir: # default "" if not config , means current dir
    LogFileName: # default monitor.log if not config
    LogRotateMaxsize:  # unit(M), default 100M if not config
    LogRotateMaxLines: # default 50W if not config